// @syndocs
import type { DocSection, MirrorDocData } from './types';

const PENDING_START = '<!-- syndocs-pending-start -->';
const PENDING_END   = '<!-- syndocs-pending-end -->';

/**
 * Render a MirrorDocData struct back to the markdown string that will be
 * written to disk.  This is the single source of truth for the file format.
 */
export function renderMirrorDoc(data: MirrorDocData): string {
  const parts: string[] = [];

  for (let i = 0; i < data.sections.length; i++) {
    const section = data.sections[i]!;

    if (i > 0) {
      // Separator before micro-doc sections
      parts.push('\n---\n');
    }

    parts.push(renderSection(data.title, section, i === 0));
  }

  return parts.join('\n').trimEnd() + '\n';
}

/**
 * Render one section (whole-file or micro-doc) to markdown.
 */
function renderSection(
  title: string,
  section: DocSection,
  isFirst: boolean,
): string {
  const lines: string[] = [];

  // Header
  if (isFirst) {
    lines.push(`# ${title}`);
  } else {
    lines.push(`## @syndocs: ${section.label}`);
  }

  // Hash stamp
  if (section.hash) {
    lines.push(`<!-- syndocs-hash: ${section.hash} -->`);
  } else {
    lines.push(`<!-- syndocs-hash: (not yet computed — run \`syndocs update\`) -->`);
  }

  lines.push('');

  // Code copy
  const lang = section.codeLanguage ?? '';
  lines.push('```' + lang);
  lines.push(section.codeCopy?.trimEnd() ?? '');
  lines.push('```');
  lines.push('');

  // Pending changes block
  if (section.pendingDiff) {
    lines.push(PENDING_START);
    lines.push(isFirst ? '## ⚠ Pending changes' : '### ⚠ Pending changes');
    lines.push('<!-- auto-generated by `syndocs check` — cleared by `syndocs update` -->');
    lines.push('```diff');
    lines.push(section.pendingDiff);
    lines.push('```');
    lines.push(PENDING_END);
    lines.push('');
  }

  // Notes
  lines.push(isFirst ? '## Notes' : '### Notes');
  lines.push('');
  if (section.notes && section.notes.trim()) {
    lines.push(section.notes.trim());
  } else {
    lines.push('> _Add documentation notes here._');
  }

  return lines.join('\n');
}

/**
 * Produce the initial content for a brand-new mirror doc.
 */
export function renderNewMirrorDoc(
  sourceFile: string,
  codeContent: string,
  codeLanguage: string,
  hash: string,
): string {
  const title = sourceFile.split('/').pop() ?? sourceFile;

  const data: MirrorDocData = {
    title,
    sections: [
      {
        kind: 'whole-file',
        hash,
        codeCopy: codeContent,
        codeLanguage,
        notes: '',
      },
    ],
  };

  return renderMirrorDoc(data);
}

/**
 * Build the content for a composed-doc embed block.
 */
export function renderEmbedBlock(
  targetPath: string,
  codeContent: string,
  codeLanguage: string,
  hash: string,
  targetLabel?: string,
): string {
  const labelPart = targetLabel ? `#${targetLabel}` : '';
  const embedLine = `@syndocs-embed: ${targetPath}${labelPart} <!-- syndocs-synced: ${hash} -->`;

  const lines = [
    embedLine,
    '```' + codeLanguage,
    codeContent.trimEnd(),
    '```',
    '',
  ];

  return lines.join('\n');
}
